"""add agent assignment fields

Revision ID: 8f4ccf881184
Revises: 68af2375bbd8
Create Date: 2026-08-23 13:20:41.836789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4ccf881184'
down_revision: Union[str, Sequence[str], None] = '68af2375bbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_agent_id'), 'orders', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_agent_id'), table_name='orders')
    op.drop_column('orders', 'agent_id')
    op.drop_column('orders', 'pickup_longitude')
    op.drop_column('orders', 'pickup_latitude')
    # ### end Alembic commands ###
