"""add agent assignment fields

Revision ID: 8f4ccf881184
Revises: 68af2375bbd8
Create Date: 2026-08-23 13:20:41.836789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4ccf881184'
down_revision: Union[str, Sequence[str], None] = '68af2375bbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely."""

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Get existing columns
    existing_columns = {
        column["name"]
        for column in inspector.get_columns("orders")
    }

    # --------------------------------------------------
    # Add pickup latitude if it does not exist
    # --------------------------------------------------

    if "pickup_latitude" not in existing_columns:
        op.add_column(
            "orders",
            sa.Column(
                "pickup_latitude",
                sa.Float(),
                nullable=True
            )
        )

    # --------------------------------------------------
    # Add pickup longitude if it does not exist
    # --------------------------------------------------

    if "pickup_longitude" not in existing_columns:
        op.add_column(
            "orders",
            sa.Column(
                "pickup_longitude",
                sa.Float(),
                nullable=True
            )
        )

    # --------------------------------------------------
    # Add agent_id if it does not exist
    # --------------------------------------------------

    if "agent_id" not in existing_columns:
        op.add_column(
            "orders",
            sa.Column(
                "agent_id",
                sa.Integer(),
                nullable=True
            )
        )

    # --------------------------------------------------
    # Create agent_id index if it does not exist
    # --------------------------------------------------

    indexes = inspector.get_indexes("orders")

    index_exists = any(
        index["name"] == "ix_orders_agent_id"
        for index in indexes
    )

    if not index_exists:
        op.create_index(
            "ix_orders_agent_id",
            "orders",
            ["agent_id"],
            unique=False
        )

    # --------------------------------------------------
    # Create foreign key if it does not exist
    # --------------------------------------------------

    foreign_keys = inspector.get_foreign_keys("orders")

    foreign_key_exists = any(
        fk.get("referred_table") == "agents"
        and fk.get("constrained_columns") == ["agent_id"]
        for fk in foreign_keys
    )

    if not foreign_key_exists:
        op.create_foreign_key(
            "fk_orders_agent_id_agents",
            "orders",
            "agents",
            ["agent_id"],
            ["id"],
            ondelete="SET NULL"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_agent_id'), table_name='orders')
    op.drop_column('orders', 'agent_id')
    op.drop_column('orders', 'pickup_longitude')
    op.drop_column('orders', 'pickup_latitude')
    # ### end Alembic commands ###
